name: matskraft
channels:
  - defaults
dependencies:
  - python=3.7.9
  - scikit-learn=0.23.2
  - pandas==1.2.4
  - numpy==1.20.3
  - pytorch==1.7.0
  - cudatoolkit=10.1
  - seaborn
  - plotly-orca
  - matplotlib=3.4.2
  - mscorefonts
# Pip-only / easier via pip
- pip:
  - transformers==4.6.1
  - tokenizers==0.10.3
  - plotly==5.18.0
  - kaleido==0.2.1
  - lxml==5.3.2
  - shapely==2.0.7
  - chemparse==0.3.2
  - nltk==3.8.1
  - GlassConversionPy==0.1.4
  - glasspy==0.3